# JuanChat config file
# poggers

# Main color to use across plugin
color: "BLUE"

# Team mode uses team colors instead of main color
# Still uses main color if player is not on a team
team-mode: false

# Permission mode uses permission colors
# Example: juanchat.green
permission-mode: false

# Ping users in chat using @<player>
ping: true

# Join, leave, whatever messages
messages:
  welcome: "§7Welcome back, <user>!"
  join: "§ajoined the server"
  leave: "§cleft the server"