# JuanChat config file
# poggers

# Main color to use across plugin
color: "BLUE"

# Team mode uses team colors instead of main color
# Still uses main color if player is not on a team
team-mode: false

# Permission mode uses permission colors
# Example: juanchat.green
permission-mode: false

# Ping users in chat using @<player>
ping: true

# JuanChat msg and reply commands
# Features stuff like moderation and well, reply
# "/juanchat togglemod" toggles conversation viewing
# for moderators
msg: true

# A builtin kill command
# Made so people kan kill themself but not others
kill: true

# Join, leave, whatever messages
messages:
  welcome: "§7Welcome back, %s!"
  join: "§8[§a+§8] %s §ajoined the server"
  leave: "§8[§c+§8] %s §cjoined the server"