name: JuanChat
version: '${version}'
main: com.github.risbun.juanchat.Main
api-version: 1.16
authors: [ThaCheeseBun,ReeZey]
description: Simple chat additions
website: https://github.com/risbun/juanchat
softdepend: [LuckPerms]
load: POSTWORLD

commands:
  alert:
    description: Send a server wide alert
    usage: /alert <message>
    permission: juanchat.command.alert
    permission-message: §cYou don't have permission to send an alert.
  f:
    description: F
    usage: /f
    permission: juanchat.command.f
    permission-message: §cYou don't have permission to pay respect.
  show:
    description: Flex your items
    usage: /show
    permission: juanchat.command.show
    permission-message: §cYou don't have permission to flex your items.

permissions:
  juanchat.command.alert:
    description: Send a server wide alert
    default: op
  juanchat.command.f:
    description: F
    default: op
  juanchat.command.show:
    description: Flex your items
    default: op
  juanchat.ping:
    description: Ping people in chat
    default: op
